model_name: tcn_video
learning_rate: 0.0001
batch_size: 40
epoch: 30
sequence_length: 4
workers: 4

# 数据集的路径
dataset_path: ../../Dataset/SAHC/even

out_features: 7  
mstcn_causal_conv: True
mstcn_layers: 12
mstcn_f_maps: 64
mstcn_f_dim: 2048
mstcn_stages: 3

train_feature_path: /home/ubuntu/disk1/Even/even/SurgicalPhaseFramework/result/feature/resnet50/resnet50_train.pkl
test_feature_path: /home/ubuntu/disk1/Even/even/SurgicalPhaseFramework/result/feature/resnet50/resnet50_test.pkl
eval_model_path: ./result/model/tcn_video/24-0.8664.model